config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.server:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brass-dalmatian.sh
        container: qc.acc_clammy-tomato-jackal
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-white-buzzard.sh
        container: qc.doc_gimpy-mustard-lobster
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-green-reindeer.sh
        container: qc.doc_whiny-ultramarine-moorhen
      github.com/cessda/cessda.cmv.server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-russet-frise.sh
        container: qc.doc_gimpy-silver-malamute
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-azure-wasp.sh
        container: qc.lic_sickly-silver-chimpanzee
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-heliotrope-cichlid.sh
        container: qc.met_stinky-beige-earwig
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.server checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-peach-worm.sh
        container: qc.sty_chewy-harlequin-quokka
      github.com/cessda/cessda.cmv.server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-fuchsia-nightingale.sh
        container: qc.sty_squeaky-cardinal-goat
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-plum-greyhound.sh
        container: qc.ver_ready-jade-chicken
timeout: 5400
